### ISSUE TITLE
Support goto

### ISSUE THREAD

**Issue by Arcesilas** [php-integrator/atom-navigation#12]
Hi,

I've never used `goto` in php, don't really like it, but... it exists...

Example:

``` php
<?php
if ($something) goto label;

// some code

label:

// some more code
```

It would make sense to be able to click on the label in `goto` statement and _go to_ that label.
##

**Comment by Gert-dev** [comment]
Agreed, marking as enhancement.

**Comment by Gert-dev** [comment]
I've relocated this [in the core](https://gitlab.com/php-integrator/core/issues/145), as the core now provides navigation.
