### ISSUE TITLE
Handle ambiguity properly.

### ISSUE THREAD

**Issue by ghost** [php-integrator/atom-navigation#20]
When two differing types share a common method, ambiguity can arise for example:

``` php
class A { public function foo() { ... } }
class B { public function foo() { ... } }

/**
 * @return A|B
 */
function bar()
{
    bar()->foo();
}

```

`foo` can refer to two different methods with possibly different documentation. We should find a way to handle this. An idea would be to show a menu that allows the user to select the match he wants to navigate to. Perhaps the intentions package will provide something similar [1].

The current behavior is just to select the first match and navigate to that.

[1] https://github.com/steelbrain/intentions/issues/15
##

**Comment by Gert-dev** [comment]
Closing this. We could theoretically support this in the core but the LSP specification currently has no provisions for this, I believe.
