### ISSUE TITLE
Deprecated selector in `php-integrator-navigation/styles/main.less`

### ISSUE THREAD

**Issue by hultberg** [php-integrator/atom-navigation#31]
Heads up for 1.13.0

In `php-integrator-navigation/styles/main.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:
- `atom-text-editor .php-integrator-navigation-navigation-possible,
  atom-text-editor::shadow .php-integrator-navigation-navigation-possible` => `atom-text-editor .php-integrator-navigation-navigation-possible,
  atom-text-editor .php-integrator-navigation-navigation-possible`
- `atom-text-editor .php-integrator-navigation-navigation-impossible,
  atom-text-editor::shadow .php-integrator-navigation-navigation-impossible` => `atom-text-editor .php-integrator-navigation-navigation-impossible,
  atom-text-editor .php-integrator-navigation-navigation-impossible`
- `atom-text-editor .comment-clickable .region,
  atom-text-editor::shadow .comment-clickable .region` => `atom-text-editor .comment-clickable .region,
  atom-text-editor .comment-clickable .region`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by Gert-dev** [comment]
Thanks for the heads up!

I think these deprecations will be fixed in the next release of this package as I've switched to hyperclick, which handles this on my behalf. I'll leave this ticket open until I know for sure, though.
