### ISSUE TITLE
Highlithing symbols of other languages in non PHP projects

### ISSUE THREAD

**Issue by Talv** [php-integrator/atom-navigation#37]
While having this plugin enabled (along with Hyperclick) for non PHP projects, it will highlight certain symbols in files of other languages. So far i've noticed it does that for: function calls in ```C```, arguments of functions in ```CoffeeScript``` (but only in docblock).
Clicking on the highlighted symbol will result in start of ```php-integrator-core``` server in the background.

In case you wouldn't be able to reproduce it, here's quick screencast:
https://gfycat.com/WiltedDetailedGreatwhiteshark

(possibly related to php-integrator/atom-base#272)

**Comment by Gert-dev** [comment]
Thanks for reporting this. It could be that the hyperclick providers aren't properly limited to just PHP. I'll have to investigate further.

**Comment by Gert-dev** [comment]
This should be fixed with 1.1.2.
