### ISSUE TITLE
Navigate to interface implementation does not work

### ISSUE THREAD

**Issue by mcharron** [php-integrator/atom-navigation#39]
Hi,

I've installed and configure php-integrator-navigation, it works. The only problem is I can't get any interface implementation by alt-clicking interface name.

The doc says "**Navigate to the definition of class, trait and interface members by alt-clicking them.**"

Can you help me ? Maybe I'm doing something wrong ?

**Comment by Gert-dev** [comment]
Hello! I see that the README is outdated, it used to be alt-click for everyone because the logic was implemented in this package. We've since migrated to using hyperclick to do the actual clicking, so the actual shortcut that is used depends on your platform.

You can configure these via the hyperclick package settings. It is likely control-click (Windows/Linux) or command-click (Mac) by default.

**Comment by mcharron** [comment]
Ok, I saw that and everything, except the **interface member** works... I don't know why.

Expectations : when Ctrl-click (Linux) on an interface name, open each classes which implements this interface

Reality : no actions. I don't understand why !

**Comment by Gert-dev** [comment]
So if I understood correctly: navigation is working for pretty much everything, just not interface implementations? Is this directly after the implements keyword?

```php
class Test implements FooInterface // Navigating to FooInterface doesn't work here
{

}
```

May I assume the interface is defined and the the appropriate namespaces (if used) are imported?

**Comment by mcharron** [comment]
@Gert-dev it works like this, I think I just misunderstood the sentence "Navigate to the definition of class, trait and interface members by alt-clicking them.".

I thought when you have this : 

```
interface FooInterface
```

When you alt-clicked on 'FooInterface' it will open **each classes which implements FooInterface**. It's not working like this ?

**Comment by Gert-dev** [comment]
@mcharron That is correct, it currently doesn't work that way. This package only handles navigation to the definition of something that is clicked.

The annotations package can show implementations and overrides of methods and properties, but that's also not entirely what you're looking for.

There currently is no package that has the described functionality, although it would be interesting to add at some point in the future. It would be something like "Find all classes that implement FooInterface".

**Comment by mcharron** [comment]
@Gert-dev ok thank you !
