### ISSUE TITLE
1.2.0 not published?

### ISSUE THREAD

**Issue by hultberg** [php-integrator/atom-navigation#40]
Hello. I noticed I'm unable to get 1.2.0 from atom registry, I get 1.1.2. Also when investigating via the atom registry api, I noticied that the latest version is 1.1.2, take a look at: https://atom.io/api/packages/php-integrator-navigation in releases.latest:
![2017-07-17_379x46](https://user-images.githubusercontent.com/1257913/28266175-c15736fa-6af3-11e7-89c9-35b12d69b593.png)

**Comment by nurtext** [comment]
Yep, same here. Download 1.20 manually, rename folder to "php-integrator-navigation" and move to `~/.atom/packages/`. Then run `npm install` in `~/.atom/packages/php-integrator-navigation/` and you're good to go.

**Comment by Gert-dev** [comment]
Something went wrong during the initial publishing of 1.2.0, causing it to be tagged but not published (unfortunately the package registry doesn't make it all too clear what's currently published).

I tagged and published 1.2.1 and I see a 1.2.1 popping up on the package registry now, but it was complaining again all the same (after which I manually forced a publish, which seems to have worked). Could you give it a try now and see if it works?

**Comment by hultberg** [comment]
Great, I got a new update now, closing. Thanks, @Gert-dev
